"""Run summary (``docs/research/execution/run_summary.json``) and the final research audit.

Both are generated only from recorded state: docs/project_status.yaml, the master
state journal and committed records. No value is typed by hand, and nothing is
reported as a result unless a result artifact exists.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from brats_uncertainty.evaluation.status import load_status
from brats_uncertainty.orchestration.state import MasterState
from brats_uncertainty.utils.git import git_commit, git_is_dirty
from brats_uncertainty.utils.io import read_json, write_json


def _maybe(path: Path) -> Any:
    return read_json(path) if path.is_file() else None


def build_run_summary(repo_root: Path, state: MasterState, cfg: dict[str, Any]) -> dict[str, Any]:
    st = load_status(repo_root)
    records = repo_root / cfg["paths"]["records_dir"]
    splits = repo_root / cfg["paths"]["splits_dir"]
    b5 = _maybe(records / "B5_manifest.json")
    return {
        "schema_version": 1,
        "generated_from": "master runner state + docs/project_status.yaml (no hand-typed values)",
        "git_commit": git_commit(repo_root),
        "git_dirty": git_is_dirty(repo_root),
        "protocol": {
            "version": st.raw["protocol"]["version"],
            "sha256": st.raw["protocol"]["sha256"],
            "tag": st.raw["protocol"]["git_tag"],
        },
        "gates": {gid: g.status for gid, g in st.gates.items() if gid[0] in "BCD"},
        "steps": {
            sid: {"status": r.status, "summary": r.summary, "attempts": r.attempts}
            for sid, r in state.steps.items()
        },
        "sessions": len(state.sessions),
        "resumes": sum(1 for s in state.sessions if s.get("resumed")),
        "dataset": {
            "acquired": bool(st.raw["data"]["acquired"]),
            "manifest_sha256": b5.get("manifest_sha256") if b5 else None,
        },
        "split_hashes": _maybe(splits / "split_hashes.json"),
        "results_available": bool(st.raw["results"]["available"]),
        "results": st.raw["results"].get("evidence"),
    }


def write_run_summary(repo_root: Path, state: MasterState, cfg: dict[str, Any]) -> Path:
    path = repo_root / cfg["paths"]["run_summary"]
    write_json(path, build_run_summary(repo_root, state, cfg), overwrite=True)
    return path


VERIFICATION_DIR = Path("results/verification")
_STOPPED = ("BLOCKED", "FAILED", "REVIEW_REQUIRED")


def final_status(results_available: bool, verification: dict[str, Any] | None) -> str:
    """The one-line verdict. REAL RESULTS VERIFIED only if every verification stage passed."""
    v = verification or {}
    if results_available and v.get("overall") == "VERIFIED":
        return "REAL RESULTS VERIFIED"
    if v.get("scientific_status") in (None, "NOT_RUN"):
        return (
            "NOT VERIFIED - no real scientific result exists yet "
            "(independent verification NOT_RUN; certificate BLOCKED)"
        )
    return (
        f"NOT VERIFIED - independent verification {v.get('overall', 'BLOCKED')} "
        f"(scientific stages {v.get('scientific_status')}); nothing unverified is published"
    )


def final_audit_text(repo_root: Path, state: MasterState, cfg: dict[str, Any]) -> str:
    """FINAL_RESEARCH_AUDIT.md from recorded state only (regenerated every session)."""
    summary = build_run_summary(repo_root, state, cfg)
    ver = _maybe(repo_root / VERIFICATION_DIR / "verification_manifest.json")
    audit = _maybe(repo_root / VERIFICATION_DIR / "consistency_audit.json") or {}
    stopped = [(sid, r) for sid, r in state.steps.items() if r.status in _STOPPED]
    lines = [
        "# Final research audit",
        "",
        "Generated by the master runner from recorded state only (docs/project_status.yaml, "
        "the master state journal, committed records and results/verification/). It is "
        "regenerated at the end of every master-run session; no value is typed by hand.",
        "",
        f"**Final status: {final_status(summary['results_available'], ver)}**",
        "",
        f"- Repository commit at generation: `{summary['git_commit']}` "
        f"(dirty: {summary['git_dirty']})",
        f"- Protocol {summary['protocol']['version']} sha256 `{summary['protocol']['sha256']}` "
        f"(tag `{summary['protocol']['tag']}`)",
        f"- Dataset manifest sha256: `{summary['dataset']['manifest_sha256']}`",
        f"- Split hashes: `{summary['split_hashes']}`",
        f"- Sessions: {summary['sessions']} (resumes: {summary['resumes']})",
        "",
        "## Stopped steps",
        "",
        *(
            [
                f"- **{sid}: {r.status}** - {r.summary}"
                + (f" Required: {r.action_needed}" if r.action_needed else "")
                for sid, r in stopped
            ]
            or ["None."]
        ),
        "",
        "## Gates",
        "",
        *(f"- {g}: {s}" for g, s in summary["gates"].items()),
        "",
        "## Steps",
        "",
        *(
            f"- {sid}: {r['status']} ({r['attempts']} attempt(s)) - {r['summary']}"
            for sid, r in summary["steps"].items()
        ),
        "",
        "## Independent result verification",
        "",
    ]
    if ver is None:
        lines.append("No verification manifest exists.")
    else:
        lines += [
            f"- Overall: **{ver.get('overall')}**; scientific stages: "
            f"**{ver.get('scientific_status')}**",
            "- Protocol: docs/research/execution/RESULT_VERIFICATION_PROTOCOL.md; report: "
            "docs/research/execution/RESULT_VERIFICATION_REPORT.md; certificate: "
            "results/verification/RESULT_VERIFICATION_CERTIFICATE.md",
            f"- Verified result values: {len(ver.get('result_index') or {})}",
            "",
            "| Stage | Status |",
            "|---|---|",
            *(f"| {st.get('title', st['id'])} | {st['status']} |" for st in ver.get("stages", [])),
        ]
    lines += ["", "## Scientific consistency audit", ""]
    questions = audit.get("questions", [])
    if questions:
        lines += ["| # | Question | Answer |", "|---|---|---|"]
        lines += [f"| {i} | {q['question']} | {q['answer']} |" for i, q in enumerate(questions, 1)]
    else:
        lines.append("Not run.")
    lines += [
        "",
        "## Results",
        "",
        f"Result evidence: `{summary['results']}`"
        if summary["results_available"]
        else "No result artifacts are published.",
        "",
    ]
    return "\n".join(lines)


def write_final_audit_for(repo_root: Path, state: MasterState, cfg: dict[str, Any]) -> Path:
    path = repo_root / cfg["paths"]["final_audit"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(final_audit_text(repo_root, state, cfg), encoding="utf-8", newline="\n")
    return path


def write_final_audit(ctx: Any) -> Path:
    """FINAL_AUDIT step (reached only after every scientific step has PASSED)."""
    from brats_uncertainty.orchestration.state import load_state

    return write_final_audit_for(ctx.repo_root, load_state(ctx.state_dir), ctx.cfg)
